# Generated by Django 4.1.3 on 2022-11-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0005_rename_druzyna_osoba_kraj'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='can_view_other_persons',
            field=models.BooleanField(default=False),
        ),
    ]
